//! Shogi4 rules engine (Rust).
//!
//! Faithful port of the decompiled official app's rules (see
//! `research/prior-art-evidence/oca-shogi4-logic-decompiled.py`) and of the Python
//! reference `engine/shogi4.py`. Validated to the digit by perft and by golden
//! position->moves files generated by the Python oracle.
//!
//! Board: 16 squares, index s = (row-1)*4 + (col-1), col,row in 1..4.
//! "Forward" = +row for player_1, -row for player_2.

use std::collections::{HashMap, HashSet, VecDeque};

pub const P1: u8 = 0;
pub const P2: u8 = 1;

// animal codes
pub const KING: u8 = 0;
pub const CARP: u8 = 1;
pub const TAPIR: u8 = 2;
pub const RACCOON: u8 = 3;
pub const FOX: u8 = 4;
pub const KOI: u8 = 5;
pub const BAKU: u8 = 6;
pub const TANUKI: u8 = 7;
pub const KITSUNE: u8 = 8;

/// base (in-hand) types, in hand-slot order
pub const BASE: [u8; 4] = [CARP, TAPIR, RACCOON, FOX];

#[inline]
fn promo(a: u8) -> u8 {
    match a { CARP => KOI, TAPIR => BAKU, RACCOON => TANUKI, FOX => KITSUNE, _ => a }
}
#[inline]
fn demote(a: u8) -> u8 {
    match a { KOI => CARP, BAKU => TAPIR, TANUKI => RACCOON, KITSUNE => FOX, _ => a }
}
#[inline]
fn base_slot(a: u8) -> usize {
    match a { CARP => 0, TAPIR => 1, RACCOON => 2, FOX => 3, _ => unreachable!() }
}

/// direction sets in (dcol, drow_forward); drow_forward is the player's forward sense
fn dirs(a: u8) -> &'static [(i8, i8)] {
    match a {
        KING => &[(-1, 0), (1, 0), (0, 1), (0, -1), (-1, 1), (1, 1), (-1, -1), (1, -1)],
        FOX => &[(-1, 0), (1, 0), (0, 1), (0, -1)],
        RACCOON => &[(-1, 1), (1, 1), (-1, -1), (1, -1)],
        CARP => &[(0, 1)],
        TAPIR => &[(0, 1), (-1, 1), (1, 1)],
        KOI | BAKU | TANUKI => &[(0, 1), (-1, 1), (1, 1), (-1, -1), (1, -1)],
        KITSUNE => &[(0, 1), (-1, 1), (1, 1), (-1, 0), (1, 0), (0, -1)],
        _ => &[],
    }
}

// ---- packed cell: 0 = empty, else 1 + animal*2 + owner ----
#[inline] fn mk_cell(owner: u8, animal: u8) -> u8 { 1 + animal * 2 + owner }
#[inline] fn c_owner(c: u8) -> u8 { (c - 1) % 2 }
#[inline] fn c_animal(c: u8) -> u8 { (c - 1) / 2 }

#[inline] fn idx(c: i8, r: i8) -> usize { ((r - 1) * 4 + (c - 1)) as usize }
#[inline] fn col(s: usize) -> i8 { (s % 4) as i8 + 1 }
#[inline] fn row(s: usize) -> i8 { (s / 4) as i8 + 1 }
#[inline] fn on(c: i8, r: i8) -> bool { (1..=4).contains(&c) && (1..=4).contains(&r) }

#[derive(Clone, Copy, Hash, PartialEq, Eq)]
pub struct Pos {
    pub board: [u8; 16],    // 0 empty, else packed cell
    pub hands: [[u8; 4]; 2], // [owner][base_slot]
    pub stm: u8,
}

#[derive(Clone, Copy, PartialEq, Eq)]
pub enum Move {
    Board { src: usize, dst: usize },
    Drop { base: u8, dst: usize },
}

fn dests(board: &[u8; 16], s: usize, owner: u8, animal: u8, out: &mut Vec<usize>) {
    let (c, r) = (col(s), row(s));
    let fwd: i8 = if owner == P1 { 1 } else { -1 };
    for &(dc, drf) in dirs(animal) {
        let (nc, nr) = (c + dc, r + drf * fwd);
        if !on(nc, nr) {
            continue;
        }
        let step = idx(nc, nr);
        out.push(step); // base step; landing legality filtered by caller
        let cell = board[step];
        if cell != 0 && c_owner(cell) == owner {
            // allied piece adjacent -> may leap to the square two out
            let (nc2, nr2) = (c + 2 * dc, r + 2 * drf * fwd);
            if on(nc2, nr2) {
                out.push(idx(nc2, nr2));
            }
        }
    }
}

pub fn legal_moves(pos: &Pos) -> Vec<Move> {
    let me = pos.stm;
    let mut moves = Vec::with_capacity(48);
    let mut buf = Vec::with_capacity(16);
    for s in 0..16 {
        let cell = pos.board[s];
        if cell == 0 || c_owner(cell) != me {
            continue;
        }
        buf.clear();
        dests(&pos.board, s, me, c_animal(cell), &mut buf);
        for &d in &buf {
            let dc = pos.board[d];
            if dc != 0 && c_owner(dc) == me {
                continue; // cannot land on an allied piece
            }
            moves.push(Move::Board { src: s, dst: d });
        }
    }
    let last_rank: i8 = if me == P1 { 4 } else { 1 };
    for bi in 0..4 {
        if pos.hands[me as usize][bi] == 0 {
            continue;
        }
        for s in 0..16 {
            if pos.board[s] == 0 && row(s) != last_rank {
                moves.push(Move::Drop { base: BASE[bi], dst: s });
            }
        }
    }
    moves
}

/// Returns (child, king_captured). If king_captured, the game is over (terminal).
pub fn make(pos: &Pos, mv: Move) -> (Pos, bool) {
    let mut p = *pos;
    let me = pos.stm;
    let mut king_cap = false;
    match mv {
        Move::Board { src, dst } => {
            let scell = p.board[src];
            let owner = c_owner(scell);
            let mut animal = c_animal(scell);
            p.board[src] = 0;
            let tcell = p.board[dst];
            if tcell != 0 {
                let ta = c_animal(tcell);
                if ta == KING {
                    king_cap = true;
                } else {
                    p.hands[me as usize][base_slot(demote(ta))] += 1;
                }
            }
            let last_rank: i8 = if me == P1 { 4 } else { 1 };
            if matches!(animal, CARP | TAPIR | RACCOON | FOX) && row(dst) == last_rank {
                animal = promo(animal); // mandatory promotion
            }
            p.board[dst] = mk_cell(owner, animal);
        }
        Move::Drop { base, dst } => {
            p.hands[me as usize][base_slot(base)] -= 1;
            p.board[dst] = mk_cell(me, base);
        }
    }
    p.stm = if me == P1 { P2 } else { P1 };
    (p, king_cap)
}

pub fn perft(pos: &Pos, depth: u32) -> u64 {
    if depth == 0 {
        return 1;
    }
    let mut total = 0u64;
    for mv in legal_moves(pos) {
        let (child, kc) = make(pos, mv);
        total += if kc { 1 } else { perft(&child, depth - 1) };
    }
    total
}

pub fn start() -> Pos {
    let mut b = [0u8; 16];
    b[idx(1, 1)] = mk_cell(P1, KING);
    b[idx(2, 1)] = mk_cell(P1, FOX);
    b[idx(3, 1)] = mk_cell(P1, RACCOON);
    b[idx(4, 1)] = mk_cell(P1, TAPIR);
    b[idx(1, 2)] = mk_cell(P1, CARP);
    b[idx(4, 4)] = mk_cell(P2, KING);
    b[idx(3, 4)] = mk_cell(P2, FOX);
    b[idx(2, 4)] = mk_cell(P2, RACCOON);
    b[idx(1, 4)] = mk_cell(P2, TAPIR);
    b[idx(4, 3)] = mk_cell(P2, CARP);
    Pos { board: b, hands: [[0; 4]; 2], stm: P1 }
}

// ---------------- golden-file encoding (must match engine/gen_golden.py) ----------------

fn animal_letter(a: u8) -> char {
    match a {
        KING => 'K', CARP => 'P', TAPIR => 'T', RACCOON => 'R', FOX => 'F',
        KOI => 'O', BAKU => 'B', TANUKI => 'N', KITSUNE => 'G', _ => '?',
    }
}
fn letter_animal(ch: char) -> u8 {
    match ch.to_ascii_uppercase() {
        'K' => KING, 'P' => CARP, 'T' => TAPIR, 'R' => RACCOON, 'F' => FOX,
        'O' => KOI, 'B' => BAKU, 'N' => TANUKI, 'G' => KITSUNE, _ => 255,
    }
}

pub fn encode_move(mv: Move) -> String {
    match mv {
        Move::Board { src, dst } => {
            format!("{}{}{}{}", col(src), row(src), col(dst), row(dst))
        }
        Move::Drop { base, dst } => {
            format!("{}@{}{}", animal_letter(base), col(dst), row(dst))
        }
    }
}

pub fn parse_pos(enc: &str) -> Pos {
    let parts: Vec<&str> = enc.split(';').collect();
    let mut board = [0u8; 16];
    for (k, ch) in parts[0].chars().enumerate() {
        if ch == '.' {
            continue;
        }
        let owner = if ch.is_ascii_uppercase() { P1 } else { P2 };
        board[k] = mk_cell(owner, letter_animal(ch));
    }
    let mut hands = [[0u8; 4]; 2];
    for (oi, hp) in [parts[1], parts[2]].iter().enumerate() {
        for (bi, d) in hp.chars().enumerate() {
            hands[oi][bi] = d.to_digit(10).unwrap() as u8;
        }
    }
    let stm = if parts[3] == "1" { P1 } else { P2 };
    Pos { board, hands, stm }
}

/// Verify each golden line: our sorted legal moves must equal the recorded moves.
/// Returns (positions_checked, mismatches).
pub fn verify_golden(path: &str) -> Result<(usize, usize), String> {
    let text = std::fs::read_to_string(path).map_err(|e| e.to_string())?;
    let (mut n, mut bad) = (0usize, 0usize);
    for line in text.lines() {
        let line = line.trim();
        if line.is_empty() {
            continue;
        }
        let (penc, want) = line.split_once(' ').ok_or("bad line")?;
        let pos = parse_pos(penc);
        let mut got: Vec<String> = legal_moves(&pos).into_iter().map(encode_move).collect();
        got.sort();
        let got = got.join(",");
        n += 1;
        if got != want {
            bad += 1;
            if bad <= 3 {
                eprintln!("MISMATCH @ {}\n  want: {}\n  got:  {}", penc, want, got);
            }
        }
    }
    Ok((n, bad))
}

// ---------------- in-RAM retrograde subgame solver (rung 2) ----------------
//
// Closed subgame = {2 kings (one per owner) + the given capturable types}. Each
// extra piece can be in either hand (base) or on the board (either owner, base or
// promoted). This mirrors engine/shogi4.py's enumerate_positions + retrograde, so
// its W/L/D counts must match the Python oracle to the unit. (Uses a HashMap index
// + explicit graph: correct and fast, but RAM-bound -- the dense ranking function +
// un-move generation that scale past RAM are the next increment.)

fn place_extras(types: &[u8], board: &[u8; 16], hands: &[[u8; 4]; 2], out: &mut Vec<Pos>) {
    if types.is_empty() {
        for stm in [P1, P2] {
            out.push(Pos { board: *board, hands: *hands, stm });
        }
        return;
    }
    let t = types[0];
    let rest = &types[1..];
    for owner in [P1, P2] {
        // option: in a hand (base)
        let mut h = *hands;
        h[owner as usize][base_slot(t)] += 1;
        place_extras(rest, board, &h, out);
    }
    for s in 0..16 {
        if board[s] != 0 {
            continue;
        }
        for owner in [P1, P2] {
            for &face in &[t, promo(t)] {
                if face == t && row(s) == if owner == P1 { 4 } else { 1 } {
                    continue; // a base piece can't sit on its promotion rank
                }
                let mut b = *board;
                b[s] = mk_cell(owner, face);
                place_extras(rest, &b, hands, out);
            }
        }
    }
}

pub fn enumerate_subgame(extra: &[u8]) -> Vec<Pos> {
    let mut out = Vec::new();
    for k1 in 0..16usize {
        for k2 in 0..16usize {
            if k1 == k2 {
                continue;
            }
            let mut b = [0u8; 16];
            b[k1] = mk_cell(P1, KING);
            b[k2] = mk_cell(P2, KING);
            place_extras(extra, &b, &[[0u8; 4]; 2], &mut out);
        }
    }
    out
}

/// Full retrograde W/L/D over the closed subgame. Returns (wins, losses, draws).
pub fn solve_subgame(extra: &[u8]) -> (u64, u64, u64) {
    let mut index: HashMap<Pos, u32> = HashMap::new();
    let mut nodes: Vec<Pos> = Vec::new();
    for p in enumerate_subgame(extra) {
        if !index.contains_key(&p) {
            index.insert(p, nodes.len() as u32);
            nodes.push(p);
        }
    }
    let n = nodes.len();
    let mut children: Vec<Vec<u32>> = vec![Vec::new(); n];
    let mut imm_win = vec![false; n];
    let mut has_move = vec![false; n];
    for (i, p) in nodes.iter().enumerate() {
        for mv in legal_moves(p) {
            has_move[i] = true;
            let (child, kc) = make(p, mv);
            if kc {
                imm_win[i] = true;
            } else {
                children[i].push(*index.get(&child).expect("subgame is closed"));
            }
        }
    }
    let mut parents: Vec<Vec<u32>> = vec![Vec::new(); n];
    for i in 0..n {
        for &j in &children[i] {
            parents[j as usize].push(i as u32);
        }
    }
    // label: 0 unknown, 1 Win, 2 Loss, 3 Draw
    let mut label = vec![0u8; n];
    let mut win_children = vec![0u32; n];
    let mut q: VecDeque<u32> = VecDeque::new();
    for i in 0..n {
        if imm_win[i] {
            label[i] = 1;
            q.push_back(i as u32);
        } else if !has_move[i] {
            label[i] = 2;
            q.push_back(i as u32);
        }
    }
    while let Some(i) = q.pop_front() {
        let li = label[i as usize];
        for k in 0..parents[i as usize].len() {
            let p = parents[i as usize][k] as usize;
            if label[p] != 0 {
                continue;
            }
            if li == 2 {
                label[p] = 1; // a child is a Loss -> parent Wins
                q.push_back(p as u32);
            } else {
                win_children[p] += 1;
                if win_children[p] as usize == children[p].len() && !imm_win[p] {
                    label[p] = 2; // all children Win -> parent Loses
                    q.push_back(p as u32);
                }
            }
        }
    }
    let (mut w, mut l, mut d) = (0u64, 0u64, 0u64);
    for i in 0..n {
        match label[i] {
            1 => w += 1,
            2 => l += 1,
            _ => d += 1,
        }
    }
    (w, l, d)
}

// ---------------- dense position ranking (the scaling bridge) ----------------
//
// A bijection `rank: position <-> [0, N)` so the value of every position lives at
// a fixed slot in a flat array (no hashing), which is what lets the retrograde
// stream off disk at full scale. Built per inventory (counts of each capturable
// type). Symbol layout for the 16-cell board multiset:
//   0 = empty, 1 = P1 king, 2 = P2 king, then 3 + ti*4 + owner*2 + face per type.
// The index = stm * S + (composition_base + multiset_permutation_rank), where a
// "composition" fixes, per type, how its copies split across the 4 board (owner,
// face) states and the 2 hands. Last-rank exclusion is NOT applied here (those
// few illegal positions are harmless holes), so N counts arrangements x 2 (turn).

fn binom(n: u64, k: u64) -> u64 {
    if k > n {
        return 0;
    }
    let k = k.min(n - k);
    let mut r: u128 = 1;
    for i in 0..k {
        r = r * (n - i) as u128 / (i + 1) as u128;
    }
    r as u64
}

/// total! / prod(counts!), where sum(counts) == total
fn multinom(counts: &[u32], total: u32) -> u64 {
    let mut r: u64 = 1;
    let mut rem = total as u64;
    for &c in counts {
        if c == 0 {
            continue;
        }
        r *= binom(rem, c as u64);
        rem -= c as u64;
    }
    r
}

fn rank_within(cells: &[u8; 16], init: &[u32]) -> u64 {
    let mut cnt = init.to_vec();
    let mut rem = 16u32;
    let mut r = 0u64;
    for p in 0..16 {
        let c = cells[p] as usize;
        for s in 0..c {
            if cnt[s] > 0 {
                cnt[s] -= 1;
                r += multinom(&cnt, rem - 1);
                cnt[s] += 1;
            }
        }
        cnt[c] -= 1;
        rem -= 1;
    }
    r
}

fn unrank_within(mut r: u64, init: &[u32]) -> [u8; 16] {
    let mut cnt = init.to_vec();
    let mut rem = 16u32;
    let mut cells = [0u8; 16];
    for p in 0..16 {
        for s in 0..cnt.len() {
            if cnt[s] > 0 {
                cnt[s] -= 1;
                let t = multinom(&cnt, rem - 1);
                if r < t {
                    cells[p] = s as u8;
                    rem -= 1;
                    break;
                }
                r -= t;
                cnt[s] += 1;
            }
        }
    }
    cells
}

fn enum_type_comps(c: u8) -> Vec<[u8; 6]> {
    // all (b00,b01,b10,b11,h1,h2) >= 0 summing to c  (4 board owner/face bins + 2 hands)
    let mut v = Vec::new();
    for b00 in 0..=c {
        for b01 in 0..=c - b00 {
            for b10 in 0..=c - b00 - b01 {
                for b11 in 0..=c - b00 - b01 - b10 {
                    for h1 in 0..=c - b00 - b01 - b10 - b11 {
                        let h2 = c - b00 - b01 - b10 - b11 - h1;
                        v.push([b00, b01, b10, b11, h1, h2]);
                    }
                }
            }
        }
    }
    v
}

pub struct Ranker {
    types: Vec<u8>,
    nsym: usize,
    type_comps: Vec<Vec<[u8; 6]>>,
    type_idx: Vec<HashMap<[u8; 6], u32>>,
    radix: Vec<u64>, // mixed-radix weight per type for the composition index
    base: Vec<u64>,  // prefix sums of multinom per composition (within one stm)
    board_counts: Vec<Vec<u32>>,
    hands: Vec<[[u8; 4]; 2]>,
    s_total: u64,
}

impl Ranker {
    pub fn new(types: &[u8], counts: &[u8]) -> Ranker {
        let nsym = 3 + 4 * types.len();
        let type_comps: Vec<Vec<[u8; 6]>> = counts.iter().map(|&c| enum_type_comps(c)).collect();
        let type_idx: Vec<HashMap<[u8; 6], u32>> = type_comps
            .iter()
            .map(|v| v.iter().enumerate().map(|(i, &t)| (t, i as u32)).collect())
            .collect();
        let total_comps: u64 = type_comps.iter().map(|v| v.len() as u64).product();
        let mut radix = vec![1u64; types.len()];
        for ti in (0..types.len()).rev() {
            radix[ti] = if ti + 1 < types.len() {
                radix[ti + 1] * type_comps[ti + 1].len() as u64
            } else {
                1
            };
        }
        let (mut base, mut board_counts, mut hands) = (Vec::new(), Vec::new(), Vec::new());
        let mut running = 0u64;
        for ci in 0..total_comps {
            let mut bc = vec![0u32; nsym];
            bc[0] = 16;
            bc[1] = 1;
            bc[2] = 1;
            bc[0] -= 2; // kings
            let mut h = [[0u8; 4]; 2];
            for ti in 0..types.len() {
                let comp = type_comps[ti][((ci / radix[ti]) % type_comps[ti].len() as u64) as usize];
                let slot = base_slot(types[ti]);
                for o in 0..2 {
                    for f in 0..2 {
                        let b = comp[o * 2 + f] as u32;
                        bc[3 + ti * 4 + o * 2 + f] = b;
                        bc[0] -= b;
                    }
                }
                h[0][slot] = comp[4];
                h[1][slot] = comp[5];
            }
            base.push(running);
            running += multinom(&bc, 16);
            board_counts.push(bc);
            hands.push(h);
        }
        Ranker { types: types.to_vec(), nsym, type_comps, type_idx, radix, base, board_counts, hands, s_total: running }
    }

    pub fn size(&self) -> u64 {
        2 * self.s_total
    }

    fn cell_to_sym(&self, cell: u8) -> usize {
        if cell == 0 {
            return 0;
        }
        let (a, o) = (c_animal(cell), c_owner(cell));
        if a == KING {
            return if o == P1 { 1 } else { 2 };
        }
        for ti in 0..self.types.len() {
            if self.types[ti] == a {
                return 3 + ti * 4 + (o as usize) * 2;
            }
            if promo(self.types[ti]) == a {
                return 3 + ti * 4 + (o as usize) * 2 + 1;
            }
        }
        unreachable!()
    }

    fn sym_to_cell(&self, sym: usize) -> u8 {
        match sym {
            0 => 0,
            1 => mk_cell(P1, KING),
            2 => mk_cell(P2, KING),
            _ => {
                let x = sym - 3;
                let (ti, rem) = (x / 4, x % 4);
                let (o, f) = ((rem / 2) as u8, rem % 2);
                let a = if f == 0 { self.types[ti] } else { promo(self.types[ti]) };
                mk_cell(o, a)
            }
        }
    }

    fn comp_index(&self, pos: &Pos) -> usize {
        let mut ci = 0u64;
        for ti in 0..self.types.len() {
            let slot = base_slot(self.types[ti]);
            let mut comp = [0u8; 6];
            comp[4] = pos.hands[0][slot];
            comp[5] = pos.hands[1][slot];
            for s in 0..16 {
                let cell = pos.board[s];
                if cell == 0 || c_animal(cell) == KING {
                    continue;
                }
                let a = c_animal(cell);
                if a == self.types[ti] {
                    comp[(c_owner(cell) as usize) * 2] += 1;
                } else if a == promo(self.types[ti]) {
                    comp[(c_owner(cell) as usize) * 2 + 1] += 1;
                }
            }
            ci += self.type_idx[ti][&comp] as u64 * self.radix[ti];
        }
        ci as usize
    }

    pub fn rank(&self, pos: &Pos) -> u64 {
        let ci = self.comp_index(pos);
        let mut cells = [0u8; 16];
        for s in 0..16 {
            cells[s] = self.cell_to_sym(pos.board[s]) as u8;
        }
        let within = rank_within(&cells, &self.board_counts[ci]);
        (pos.stm as u64) * self.s_total + self.base[ci] + within
    }

    pub fn unrank(&self, i: u64) -> Pos {
        let stm = (i / self.s_total) as u8;
        let r = i % self.s_total;
        let ci = self.base.partition_point(|&b| b <= r) - 1;
        let within = r - self.base[ci];
        let cells = unrank_within(within, &self.board_counts[ci]);
        let mut board = [0u8; 16];
        for s in 0..16 {
            board[s] = self.sym_to_cell(cells[s] as usize);
        }
        Pos { board, hands: self.hands[ci], stm }
    }
}

/// True unless a base (unpromoted) piece sits on its owner's promotion rank.
pub fn is_legal(pos: &Pos) -> bool {
    for s in 0..16 {
        let cell = pos.board[s];
        if cell == 0 {
            continue;
        }
        let (a, o) = (c_animal(cell), c_owner(cell));
        if matches!(a, CARP | TAPIR | RACCOON | FOX) && row(s) == if o == P1 { 4 } else { 1 } {
            return false;
        }
    }
    true
}

/// Retrograde W/L/D over a **flat value array indexed by `rank`**, with child edges
/// generated on the fly (`make` + `rank`) — no stored graph. This is the scalable
/// solver mechanism in miniature (the full solve adds un-move-gen + push + external
/// memory). Pull-based Jacobi fixpoint; fine for subgames. Returns (wins, losses, draws)
/// over legal positions.
pub fn solve_flat(types: &[u8], counts: &[u8]) -> (u64, u64, u64) {
    const UNK: u8 = 0;
    const WIN: u8 = 1;
    const LOSS: u8 = 2;
    let rk = Ranker::new(types, counts);
    let n = rk.size() as usize;
    let mut val = vec![UNK; n];
    loop {
        let mut changed = false;
        for i in 0..n {
            if val[i] != UNK {
                continue;
            }
            let pos = rk.unrank(i as u64);
            if !is_legal(&pos) {
                continue;
            }
            let (mut can_win, mut found_loss, mut all_win, mut any) = (false, false, true, false);
            for mv in legal_moves(&pos) {
                any = true;
                let (child, kc) = make(&pos, mv);
                if kc {
                    can_win = true; // capturing the king ends the game — immediate win
                    continue;
                }
                match val[rk.rank(&child) as usize] {
                    LOSS => found_loss = true,
                    WIN => {}
                    _ => all_win = false, // an undecided child blocks a Loss verdict
                }
            }
            let nv = if can_win || found_loss {
                WIN
            } else if !any || all_win {
                LOSS
            } else {
                UNK
            };
            if nv != UNK {
                val[i] = nv;
                changed = true;
            }
        }
        if !changed {
            break; // leftover UNKNOWN legal positions are Draws (repetition convention)
        }
    }
    let (mut w, mut l, mut d) = (0u64, 0u64, 0u64);
    for i in 0..n {
        if !is_legal(&rk.unrank(i as u64)) {
            continue;
        }
        match val[i] {
            WIN => w += 1,
            LOSS => l += 1,
            _ => d += 1,
        }
    }
    (w, l, d)
}

/// Verification: a single FORWARD pass checking every value is locally minimax-
/// consistent with its children. A labeling that passes everywhere, with correct
/// terminals (king-capture wins), is the unique correct solution — so 0 violations
/// certifies the tablebase. No un-move-gen, no fixpoint iteration: this is the
/// "verify for a fraction of the solve" pass. Returns the violation count.
pub fn audit_solution(rk: &Ranker, val: &[u8], legal: &[bool]) -> u64 {
    let n = rk.size() as usize;
    let mut bad = 0u64;
    for i in 0..n {
        if !legal[i] {
            continue;
        }
        let pos = rk.unrank(i as u64);
        let (mut imm_win, mut has_loss, mut has_draw) = (false, false, false);
        for mv in legal_moves(&pos) {
            let (child, kc) = make(&pos, mv);
            if kc {
                imm_win = true;
                continue;
            }
            match val[rk.rank(&child) as usize] {
                V_LOSS => has_loss = true,
                V_WIN => {}
                _ => has_draw = true, // V_UNK == Draw
            }
        }
        let ok = match val[i] {
            V_WIN => imm_win || has_loss,                  // can win now or move to a Loss
            V_LOSS => !imm_win && !has_loss && !has_draw,  // every move leads to a Win
            _ => !imm_win && !has_loss && has_draw,        // Draw: no win, but holds a draw
        };
        if !ok {
            bad += 1;
        }
    }
    bad
}

// ---------------- un-move generation (predecessors) ----------------
//
// The hard primitive for push-based retrograde: given q, produce every legal
// position p with a legal move p -> q. We generate candidates by reversing each
// forward-move shape (board move, capture, promotion, drop) and **verify each by
// running `make` forward** — so correctness rides on the already-validated engine,
// not on hand-written reverse logic. Material is conserved, so all predecessors
// share q's inventory.

/// Is this specific move legal in `p`? (Direct check — no full move-gen.)
fn move_is_legal(p: &Pos, mv: Move) -> bool {
    let me = p.stm;
    match mv {
        Move::Board { src, dst } => {
            let sc = p.board[src];
            if sc == 0 || c_owner(sc) != me {
                return false;
            }
            let dc = p.board[dst];
            if dc != 0 && c_owner(dc) == me {
                return false; // can't land on own piece
            }
            let mut buf = Vec::with_capacity(12);
            dests(&p.board, src, me, c_animal(sc), &mut buf);
            buf.contains(&dst)
        }
        Move::Drop { base, dst } => {
            p.hands[me as usize][base_slot(base)] > 0
                && p.board[dst] == 0
                && row(dst) != if me == P1 { 4 } else { 1 }
        }
    }
}

fn add_if_pred(p: Pos, mv: Move, q: &Pos, set: &mut HashSet<Pos>) {
    if !is_legal(&p) || !move_is_legal(&p, mv) {
        return;
    }
    let (child, kc) = make(&p, mv);
    if !kc && child == *q {
        set.insert(p);
    }
}

pub fn predecessors(q: &Pos) -> Vec<Pos> {
    let y = if q.stm == P1 { P2 } else { P1 }; // the player who just moved
    let x = q.stm; // the player whose piece could have been captured
    let mut set: HashSet<Pos> = HashSet::new();
    let empties: Vec<usize> = (0..16).filter(|&s| q.board[s] == 0).collect();

    for dst in 0..16 {
        let cell = q.board[dst];
        if cell == 0 || c_owner(cell) != y {
            continue;
        }
        let a_now = c_animal(cell);

        // (1) reverse a DROP: a freshly-dropped piece is a Y-owned base piece.
        if matches!(a_now, CARP | TAPIR | RACCOON | FOX) {
            let mut p = *q;
            p.board[dst] = 0;
            p.hands[y as usize][base_slot(a_now)] += 1;
            p.stm = y;
            add_if_pred(p, Move::Drop { base: a_now, dst }, q, &mut set);
        }

        // (2) reverse a BOARD move. The mover sits at dst now; it came from some
        //     empty `src`, and may have promoted on arrival and/or captured at dst.
        let on_y_last = row(dst) == if y == P1 { 4 } else { 1 };
        let promoted = matches!(a_now, KOI | BAKU | TANUKI | KITSUNE);
        let pre_forms: &[u8] = if on_y_last && promoted {
            &[] // filled below
        } else {
            std::slice::from_ref(&a_now)
        };
        let pre_two = [demote(a_now), a_now];
        let pre_forms: &[u8] = if on_y_last && promoted { &pre_two } else { pre_forms };

        for &a_pre in pre_forms {
            for &src in &empties {
                if src == dst {
                    continue;
                }
                // (2a) no capture: dst was empty before the move
                let mut p = *q;
                p.board[src] = mk_cell(y, a_pre);
                p.board[dst] = 0;
                p.stm = y;
                add_if_pred(p, Move::Board { src, dst }, q, &mut set);

                // (2b) capture: dst held an X-piece that demoted into Y's hand
                for t in [CARP, TAPIR, RACCOON, FOX] {
                    if q.hands[y as usize][base_slot(t)] == 0 {
                        continue;
                    }
                    let on_x_last = row(dst) == if x == P1 { 4 } else { 1 };
                    for promoted_cap in [false, true] {
                        if !promoted_cap && on_x_last {
                            continue; // a base X-piece can't sit on X's last rank
                        }
                        let cap = if promoted_cap { promo(t) } else { t };
                        let mut p = *q;
                        p.board[src] = mk_cell(y, a_pre);
                        p.board[dst] = mk_cell(x, cap);
                        p.hands[y as usize][base_slot(t)] -= 1;
                        p.stm = y;
                        add_if_pred(p, Move::Board { src, dst }, q, &mut set);
                    }
                }
            }
        }
    }
    set.into_iter().collect()
}

// Value codes in the flat array.
pub const V_UNK: u8 = 0; // (legal & undecided after fixpoint = Draw; illegal slots also 0)
pub const V_WIN: u8 = 1;
pub const V_LOSS: u8 = 2;

/// Left–right mirror of a position (columns c ↔ 5−c). The rules are LR-symmetric,
/// so `value(pos) == value(mirror(pos))` — the basis of the ~2× symmetry fold.
pub fn mirror(pos: &Pos) -> Pos {
    let mut board = [0u8; 16];
    for s in 0..16 {
        if pos.board[s] != 0 {
            board[idx(5 - col(s), row(s))] = pos.board[s];
        }
    }
    Pos { board, hands: pos.hands, stm: pos.stm }
}

/// Push-based retrograde over the rank-indexed flat array (the algorithm the full
/// external-memory solve runs). Returns the ranker, the value array (`V_*` per slot),
/// and a legality mask.
pub fn solve_push_array(types: &[u8], counts: &[u8]) -> (Ranker, Vec<u8>, Vec<bool>) {
    let rk = Ranker::new(types, counts);
    let n = rk.size() as usize;
    let mut val = vec![V_UNK; n];
    let mut cnt = vec![0u16; n]; // undecided non-king-capture children
    let mut legal = vec![false; n];
    let mut q: VecDeque<u64> = VecDeque::new();

    // init: one forward pass to count children + seed terminals
    for i in 0..n {
        let pos = rk.unrank(i as u64);
        if !is_legal(&pos) {
            continue;
        }
        legal[i] = true;
        let (mut imm_win, mut deg) = (false, 0u16);
        for mv in legal_moves(&pos) {
            let (_c, kc) = make(&pos, mv);
            if kc {
                imm_win = true;
            } else {
                deg += 1;
            }
        }
        cnt[i] = deg;
        if imm_win {
            val[i] = V_WIN;
            q.push_back(i as u64);
        } else if deg == 0 {
            val[i] = V_LOSS;
            q.push_back(i as u64);
        }
    }

    // propagate backward via un-move generation
    while let Some(qi) = q.pop_front() {
        let qpos = rk.unrank(qi);
        let qv = val[qi as usize];
        for p in predecessors(&qpos) {
            let pi = rk.rank(&p) as usize;
            if val[pi] != V_UNK {
                continue;
            }
            if qv == V_LOSS {
                val[pi] = V_WIN; // a move to a Loss => Win
                q.push_back(pi as u64);
            } else {
                cnt[pi] = cnt[pi].saturating_sub(1);
                if cnt[pi] == 0 {
                    val[pi] = V_LOSS; // all children Win => Loss
                    q.push_back(pi as u64);
                }
            }
        }
    }
    (rk, val, legal)
}

/// W/L/D counts over legal positions.
pub fn solve_push(types: &[u8], counts: &[u8]) -> (u64, u64, u64) {
    let (_rk, val, legal) = solve_push_array(types, counts);
    let (mut w, mut l, mut d) = (0u64, 0u64, 0u64);
    for i in 0..val.len() {
        if !legal[i] {
            continue;
        }
        match val[i] {
            V_WIN => w += 1,
            V_LOSS => l += 1,
            _ => d += 1,
        }
    }
    (w, l, d)
}
